name: Release
on:
  schedule:
    - cron: '0 0 * * SAT'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y-%m-%d"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Release
        env:
          VERSION: ${{ steps.calver.outputs.release }}
        run: |
          ./gradlew publishMavenPublicationToSonatypeStagingRepository  \
            -PreleaseVersion="$VERSION" \
            -PossrhUsername="$OSSRH_USERNAME" \
            -PossrhPassword="$OSSRH_PASSWORD" \
            -PsigningKey="$GPG_SIGNING_KEY" \
            -PsigningKeyId="$GPG_SIGNING_KEY_ID" \
            -PsigningPassword="$GPG_SIGNING_PASSWORD"
